apiVersion: v1
kind: Service
metadata:
  name: clap-api-service
spec:
  type: NodePort
  selector:
    app: clap-api
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clap-api
  name: clap-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clap-api
  template:
    metadata:
      labels:
        app: clap-api
    spec:
      containers:
        - name: clap-api
          image: clap-api
          ports:
            - containerPort: 3000