name: Update K8s manifests
on:
  workflow_call:
    inputs:
      newImage:
        required: true
        type: string

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          name: feeeeliipe/clap-api
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
      - name: Set new version to K8s manifest
        run: |
          ls
          cd k8s/
          kustomize edit set image clap-api=${{ inputs.newImage }}
      - name: Commit updates on K8s manifest
        run: |
          git config user.email "demo@actions.com"
          git config user.name "GH Actions Pipeline"
          git add .
          git commit -m "Updating k8s manifest with new version"
      - name: Push Changes
        uses: ad-m/github-push-action@master
  